fix(breakpoints): multiple responsive style props
smooth-code/xstyled pull request #141
Opened 2020-10-27 21:45 UTC by EmilioAiolfi

## Summary

Hello folks!
There is a bug when passing several responsive style props, the order of the resulting media queries is wrong.
More details on this in issue [#119](https://github.com/smooth-code/xstyled/issues/119)
Example 
Code:
```
<Box 
  pt={{ sm: 0, lg: 60 }}
  pb={{ md: 20, lg: 60 }}
  bg ={{ xs: 'blue', md: 'red', lg: 'green', xl: '#000000'}}
>
  hello
</Box>
```
![Screen Shot 2020-10-27 at 6 39 56 PM](https://user-images.githubusercontent.com/999120/97365309-3e9a9580-1884-11eb-9d75-60fb01ab33da.png)

## Test plan
The idea is to organize the order of @medias based on the breakpoint values. A function was created to guarantee the order of the breakpoints, without the need to add complexity to the `merge` function.
![Screen Shot 2020-10-27 at 6 39 20 PM](https://user-images.githubusercontent.com/999120/97365364-52de9280-1884-11eb-8c8b-f7cc88e18f4a.png)

2020-10-28 06:40 UTC, gregberge commented
Hello @EmilioAiolfi, thanks for this fix! I have to find a way to test it and I think it could alter performances. All xstyled code is heavily optimized, I see a reduce, etc.. It is probably not as performant as expected. I will give a deeper look to fix it based on your work.

2020-10-28 18:49 UTC, EmilioAiolfi commented
I tried to help with this bug by understanding it as something serious, by compromising the use of breakpoints. The problem is to expect a responsibility that I believe would not be the 'util/merge' function. Something like being responsible for @media's orders, and it's something that the merge function really shouldn't know.
About the approach I suggested. it is just one option among so many, but I expected a code review to help with this bug and we managed to solve it.

About this bug is the point of attention about the use of `util/merge` in [reduceBreakpoints](https://github.com/smooth-code/xstyled/blob/master/packages/system/src/style.js#L125) and [`compose`](https://github.com/smooth-code/xstyled/blob/master/packages/system/src/style.js#L194)

Thanks for @xstyled! I believe in the approach it offers and I insist on trying to help improve it more and more.

2020-11-02 22:20 UTC, gregberge requested changes
Small perf improvements.

2020-11-02 22:20 UTC, gregberge commented on packages/system/src/style.js
> +    const isValid = Object.keys(styles).includes(currentMediaKey);
Please extract `Object.keys(styles)` out of the `for` to avoid doing it in each iteration.

2020-11-02 22:20 UTC, gregberge commented on packages/system/src/style.js
> +  const breakpoints = Object.values(getBreakpoints(props))
Please use `Object.keys` instead (ES5 & perf). Then iterate on it and get the breakpoint from `const breakpoint = breakpoints[key]`.

2020-11-04 18:28 UTC, merged

2020-11-04 18:28 UTC, gregberge commented
Thanks!